on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Backend build
        run: docker build ./backend -t link-shortener-challenge/api

      - name: Backend setup
        run: docker run -d \
          -p 3333:3333 \
          --name link-shortener-challenge-api \
          --rm link-shortener-challenge/api

      - name: Evaluator step
        id: evaluator
        uses: carlos8v/vitest-evaluator-action@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
