on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Evaluator step
        id: evaluator
        uses: carlos8v/vitest-evaluator-action@v2.4
        with:
          test-coverage: 100
          token: ${{ secrets.GITHUB_TOKEN }}
